apiVersion: ENC[AES256_GCM,data:uVk=,iv:v1MzJwR2iWXZBPbt1GfZ88aZvKW7NO+B17jSUvlOzrI=,tag:0x3A+ETrVFD/Hdwr8VaDZQ==,type:str]
kind: ENC[AES256_GCM,data:z2t08psu5/KY,iv:fA1ZMNEglQEYecLggQLHf9Zsew02gNhFSU7KzSOUqbs=,tag:5zQDqIRtQ3/5v37gJEP0tw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:RD4AyjWvNwyZU3ypLY2OtA==,iv:mlrqdXoE46D4tIQcaFjj69qRYE3g0I2da1U9ey0fVHM=,tag:sWlBhthuu7IAnjHYQRPv5A==,type:str]
    namespace: ENC[AES256_GCM,data:ZdePRI10DC0U,iv:StFYx/ez2p0fYWwpjhbc00ET1T6We2OyzEp9slIsGRQ=,tag:kX4k0FmuQVwIMG51r6L6XQ==,type:str]
data:
    APP_URL: ENC[AES256_GCM,data:c1cfup83BTdhoVtZBQTfg39+3kIY,iv:AUaENC3xRv6paj/cKvl3HwiTVKsJVL6ybGmHscKi1wo=,tag:uefUbrVVGHIc6IM7iAbhYA==,type:str]
    #ENC[AES256_GCM,data:90Ey1EjTxh8WYNenS46maZl22dd2hXpKiCDSjEI3qbMXgIDjjyKGbv3sTfw6sOXyDp3pi5DBMkWh4fzszUsaKH0=,iv:hyPbvx1ecKnlYFiBOFvusgtDBkw9CnDzipkWKeczZ+Q=,tag:VLCm9FKEdJ5GPRQm4P+M+Q==,type:comment]
    TRUST_PROXY: ENC[AES256_GCM,data:82ytuA==,iv:pIIvs8UP2f7LGccvrwh/fcSLLBzLjyZlZOI4kNx1qFQ=,tag:/y2g7pLztKOAHnmGFCSROg==,type:str]
    #ENC[AES256_GCM,data:z28TVQ+zsQ20TXfZ3xwrXXkSdWoqkiox++pZlcw2MLXh35Etc6Lk,iv:/Pc3iZZKVuAgr5+AUyDoB7Q1wLsqanqZkODkbJhiP0E=,tag:D5eosDRyalZ4fgSIPoHs7w==,type:comment]
    DB_PROVIDER: ENC[AES256_GCM,data:2vc5grnvgXM=,iv:YfwL/6uT5z7PFal/d5JiDVfpUa+wUIFfq6Tyj4cFK3Y=,tag:agqmLgZsMV1po8dMcTz3Bg==,type:str]
    DB_CONNECTION_STRING: ENC[AES256_GCM,data:8UiO2rmSuytiNXqNbcI9FPduntr5uFdeuFuJPEB/2qBha2HQcS92RvxhC3QB4aOsTC0EqesDBqQUV7BZF6rHiTb1U9lrwvYYu7EIaHx/UqjM0Zmhrvvu0N2vZjHszHbW+TyM7ZreI2DhNM2i5UJaAacU0EK6BmSd1MlTDWw6kVNaS1uT,iv:OXABKCjaXaQprcoTEinTpNdjDqgglidE/lPXAzyJK7Y=,tag:ZrwpccLqfAovYk54EHaUwA==,type:str]
    KEYS_STORAGE: ENC[AES256_GCM,data:XcS5ESQ4YGw=,iv:PBy0eJxl1z9LDFIOVP1b0Al/O2XK/o7P1pfq6aPkGIc=,tag:9oON9gb2KFqI8coiedG1KA==,type:str]
    ENCRYPTION_KEY: ENC[AES256_GCM,data:oi6J/pOlCIluU+YHVTK5jmYRfYfczJNZOzl9JVzKyR/iSdmM4o5k6bt0v9U=,iv:sqqBPCV9R2lXNfT2VQhOUd6Vh2OqTkGSTusn0O9eX0o=,tag:PF6BU47wh0zcK1n/womicQ==,type:str]
sops:
    lastmodified: "2025-11-03T17:45:59Z"
    mac: ENC[AES256_GCM,data:kiq2s/Gv/P+PoevlENcz60zrdrwpTHwOq8oM5vVQN1VdE+s3ZbUk5S8ACbfa+N1j80giC6XaGU570K31Zr7y1l1iY7kVl5QMPAh6l9xn9GnC3Rdfqy/Oe2IKW+2sXZENcE+172f1rTL0u3YxGXKd87dOH+jM49C/8HOkHN5xxow=,iv:gQMmdWN/+pEfyGYU5lNCPbiDLavHcOorIfLYb/R+Bxo=,tag:G1tDA4/asj8Gmt470o0/mQ==,type:str]
    pgp:
        - created_at: "2025-11-03T17:45:59Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hMIDn615Jx19RhwSBCMEAX9lgUiaRb45wyAQEUv/B/TYSp0Z+SfspEed0YXwX1s5
            +4pFdjw1kLfbM0UyQKq7oiF/Doo2MCRjXLesVc9NZIfiAXPf3ap9BNKCbG6Vd1nZ
            pTYRRCJmIzqdvUBeJuxLNCIM1S7fRiAex8b0OI/obfkIRNDrWFD9s9hOkT8C9WmA
            fvfRMLL13xIWPe+QUQpA310o7MpC58p4mZzPiVVTf5Uos2IzOSZCahK/coJRRbST
            cup4S9JeATE/a3Stp1yQ2UMhGs4LdxH4M8idIWDxG4u1279gIyaEe/3mE8YOyi5v
            5TKhKOtCKUDct6WtL4CoFTmIgxnmUlx9sdHJ+WsIlDLHQhVXrjF5pnk4Xj+YhCVm
            YND1TA==
            =W2/u
            -----END PGP MESSAGE-----
          fp: F01B47BAD5FC895EE1F1B9E59FAD79271D7D461C
    unencrypted_suffix: _unencrypted
    version: 3.11.0
