---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pocket-id
  namespace: pocket-id
spec:
  replicas: 1
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: "homeserver"

      containers:
        - name: pocket-id
          image: ghcr.io/pocket-id/pocket-id:v1
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 1411
              protocol: TCP
          envFrom:
            - configMapRef:
                name: pocket-id-config
          volumeMounts:
            - name: data
              mountPath: /app/data
          readinessProbe:
            exec:
              command:
              - /app/pocket-id
              - healthcheck
            initialDelaySeconds: 10
            periodSeconds: 300

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pocket-id-data
---
apiVersion: v1
kind: Service
metadata:
  name: pocket-id
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: pocket-id
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pocket-id
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-all
    traefik.ingress.kubernetes.io/router.entryPoints: 'websecure'
    traefik.ingress.kubernetes.io/router.tls: true
spec:
  ingressClassName: traefik
  tls:
    - hosts:
      - key.rmtt.tech
      secretName: pocket-id-tls
      

  rules:
    - host: key.rmtt.tech
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name:  pocket-id
                port:
                  number: 80
