apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app: pocket-id
    includeSelectors: true
    includeTemplates: true

namespace: pocket-id

resources:
  - namespace.yaml
  - configmap.yaml.dec
  - pvc.yaml
  - deployment.yaml
