hostname: ENC[AES256_GCM,data:zv6uvLxxdaUm,iv:FIwouxp1ZTQ5nusbdn48P0QgXQTavtcpNiVG1M+LLpc=,tag:mLzLL1aGMJcOBXL8QSBgnQ==,type:str]
app_url: ENC[AES256_GCM,data:jB9aIPUq+DBO3R8fUw==,iv:dOAsk7WmHGzrX/NX+9qec9x3BFs19Ks1ydZjdeaZfWw=,tag:EMF8WXMm3d3e1phFYFWI5A==,type:str]
encryption_key: ENC[AES256_GCM,data:jbyEBBIjusaOzuJ1bEE+rLSrv4F7fQG8eVIfKbVix3G3zw3jS3yejnbCTiA=,iv:YcS8kahkoV1fpjQFNjTgIN29Qbfj5kPjoDRJgic/nUs=,tag:D2VXZiVr3iXWDl79mhA5DA==,type:str]
sops:
    lastmodified: "2026-01-18T03:43:58Z"
    mac: ENC[AES256_GCM,data:2r0Ld/3hLJ+WzBrG3phR71o8VxQ4z8UEYBd9sZPDdEGfPI5fUQtVWnSwEXLoM7e2zCSh/aBrZwPCDLvsGtAR9iuAM1pL/7ncgn89fHcGyOxKEoG4wEMwfvpYq6AhfBXs0dAuA15PyV+LhvJIG8Ty0ybo3aVyWmsKy03C/CxZEG0=,iv:TFotkf3tc2MvMscwrO9wOKEQnaH+j+Il6FOLy4QABR4=,tag:VNXDS6ulH70qKIMu+vxT1g==,type:str]
    pgp:
        - created_at: "2026-01-11T14:34:03Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hMIDn615Jx19RhwSBCMEAYVrI22IaLX4Qe0kPqkqJ2UHq3NClDZZfnag5PbvNynT
            cO3mSlnH6+3GtB3/MMKI2oPARxmlaOIEEfG4/57JNJ23AdubQAzCgUPeZ3M8TMm7
            tTXme386qtPZqbVvtgnONYNVuXdwLpOoHEYtXRMjxqme6bIC217TQp34AIUY4rhM
            JHhHMARUhFN82TqONvx1Btv++Vek21pRqPjrbJA4bpEpz64JH0Jn8g2YG8PcJt7S
            QdoTwtJeAaZgL5lTNpdn6CAwJFRM6K0Ei5yINzG0n2gN3lIqmO1hYKsmHopuz3vA
            H+hGGvw0JKduAGIBaT8haMpzA6ay+Qcy1ZOA6AukDV4h6rkS2fivyWjrnLVc+/3u
            wQCPNA==
            =YdXk
            -----END PGP MESSAGE-----
          fp: F01B47BAD5FC895EE1F1B9E59FAD79271D7D461C
    unencrypted_suffix: _unencrypted
    version: 3.11.0
